dependencies:
- alias: zeebe
  name: zeebe-cluster
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.128
- alias: operate
  name: zeebe-operate
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.24
- alias: tasklist
  name: zeebe-tasklist
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
  condition: "tasklist.enabled"
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.26.2
