dependencies:
- alias: zeebe
  name: zeebe-cluster
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.22
- alias: operate
  name: zeebe-operate
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.19.0
